### ISSUE TITLE
Problem with read_msg in a loop

### ISSUE THREAD

**Issue by antuki** [hrbrmstr/msgxtractr#2]
Hi again, 

Now i'm trying to read my 10000 .msg I wanted to use for a text mining exercise. 

But when i'm doing a loop or a lapply to read them, it does not seem to be able to treat them if I use more than around 500 emails : 

 for example : 

> liste <- NULL
> for(i in dir("C:/Users/Desktop/TOTO")){
>   msg <- read_msg(paste0("C:/Users/Desktop/TOTO",i))
 > liste[[i]] <- c(msg$header$Date, msg$sender$sender_name, msg$display_envelope$display_to,msg$subject,msg$body)
> }

all liste[[i]]$text are filled from 1 to 509 but then from 510 to 10 000 it's NULL

> liste[[508]][1]
[[1]]
[1] "Thu, 27 Jul 2017 11:22:18 +0000"

> liste[[509]][1]
[[1]]
[1] "Fri, 10 Mar 2017 16:23:47 +0100"

> liste[[510]][1]
$text
NULL

> liste[[511]][1]
$text
NULL

... etc. 

And I obtain the same error when i'm doing 3 loops of 250 elements for the 3rd one. 

Then, when I quit Rstudio it never wants me to save the project, showing the following error (which may be linked with what i said above) : 

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/Desktop/test_mails/.RDataTmp', probable reason 'Too many open files'
Error: Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In file.remove(outfile) :
  cannot remove file 'C:/Users/Desktop/test_mails/.RDataTmp', reason 'No such file or directory'

Any idea of the source of the problem ? Any solution for me ? 

Thank you !

**Comment by hrbrmstr** [comment]
looks like I might have missed a pointer clearing (though I did a full check with valgrind and it didn't find anything wrong mem-free-wise). Lemme try replicating your setup by reading in my test message many times.

thx, for persisting with this! the issue filing really helps catch edge cases and mis-steps in the code.

**Comment by hrbrmstr** [comment]
OH waitaminute!

(I was copying & pasting this over to my rstudio session to read in more detail).

It's entirely possible that the C++ library code I'm using didn't close the file properly. Hopefully that's it.

A++ issue, btw. code + error message rly rly helped!

**Comment by hrbrmstr** [comment]
OK, I just pushed up a version that does indeed now close the file (that looks like what was causing the problem).

Also, you might find this idiom useful:

    library(tidyverse)

    dir("C:/Users/Desktop/TOTO", full.names=TRUE) %>% 
      map_df(~{
        list(
          date = msg$header$Date %||% NA, 
          sender_name = msg$sender$sender_name %||% NA, 
          display_to = msg$display_envelope$display_to %||% NA,
          sugject = msg$subject %||% NA,
          body = msg$body$text %||% NA
        )
      })

That will get you a data frame of all the messages in that directory. the `%||% NA` is a nice trick when the result of the list extraction is `NULL` but you still want to show there's no value for it when building a data frame.

Also, be careful to use either `$text` or `$html` entries of the `$body` sub-list since it can have both.

You may also find using `anytime::anytime()` on the resultant `date` column handy in getting that column converted nicely to a timestamp (even if the string is in different formats for different msgs).

**Comment by antuki** [comment]
Thank you, the loop is now working. 

Thank you for the idiom but it seems that there is a part missing (it does'nt understand what "msg" means and there is no read_msg in it) ? Can you show me a complete example so that I can undertand how it works ? (I didn't try the purrr package yet and it's a way to have a first try). 

And a last thank you for the anytime package trick.

I may post other issues in the future because I've noticed that some of my e-mails are not properly read (the length of msg$body$text is 9 and always the same even with different msgs and senders : with strange letters). I may inverstigate it a bit later...

**Comment by hrbrmstr** [comment]
argh. fixed the example.

those small messages may be RTF formatted. I don't have any of those to play with and it's a different field (that requires handling of 2 edge cases and then also adding 2 fields to the returned `list` to make the RTF actually usable (one rtf_text and rtf_html since it's possible to have text, html and rtf bodies all at the same time).

I may have an old Windows VM w/Office on a drive somewhere. If so, I'll try to gen some messages with diverse attributes.

**Comment by davidski** [comment]
Had to post to this closed issue only because of the `%||%` trick in https://github.com/hrbrmstr/msgxtractr/issues/2#issuecomment-325215532, which is a clean solution for another `purrr` issue I was having last night. :)
